In [1]:
from pettingzoo.mpe import simple_tag_v2
from gymnasium.utils.save_video import save_video

import time
import numpy as np

In [2]:
env = simple_tag_v2.env(num_good=1, 
                        num_adversaries=3, 
                        num_obstacles=2, 
                        max_cycles=50000, 
                        continuous_actions=True, 
                        render_mode="human"
)

In [3]:
env.reset()
i = 0
for agent in env.agent_iter():

    print(agent, ':')
    print(env.last())
    # print(env.rewards[agent])
    env.step(env.action_space(agent).sample())
    print(env.observe(agent))
    # observation space: shape(14),(16)
    # Agent and adversary observations: [self_vel, self_pos, landmark_rel_positions, other_agent_rel_positions, other_agent_velocities]
    # observation function in the simple_tag.py: other_agent_rel_positions contains all agents except oneself, the order is adversary to agent,
    # other_agent_velocities only for not adversary

    i = i + 1
    if i == 4:
        break

env.close()

adversary_0 :
(array([ 0.        ,  0.        ,  0.28114784, -0.10467174,  0.49858594,
       -0.4031773 , -0.30692732,  0.64155465,  0.19227125,  0.14148666,
        0.44570836,  0.3249428 ,  0.7032439 ,  0.9045745 ,  0.        ,
        0.        ], dtype=float32), 0.0, False, False, {})
[ 0.          0.          0.28114784 -0.10467174  0.49858594 -0.4031773
 -0.30692732  0.64155465  0.19227125  0.14148666  0.44570836  0.3249428
  0.7032439   0.9045745   0.          0.        ]
adversary_1 :
(array([ 0.        ,  0.        ,  0.4734191 ,  0.03681492,  0.30631468,
       -0.54466397, -0.4991986 ,  0.500068  , -0.19227125, -0.14148666,
        0.2534371 ,  0.18345612,  0.5109727 ,  0.76308787,  0.        ,
        0.        ], dtype=float32), 0.0, False, False, {})
[ 0.          0.          0.4734191   0.03681492  0.30631468 -0.54466397
 -0.4991986   0.500068   -0.19227125 -0.14148666  0.2534371   0.18345612
  0.5109727   0.76308787  0.          0.        ]
adversary_2 :
(array([ 0.   

In [9]:
env.reset()
count = 0

aa = np.array([0.0548357,  0.   ,      0.       ,  0.02204804, 0.        ])
for agent in env.agent_iter():
    observation, reward, termination, truncation, info = env.last()
    action = None if termination or truncation else env.action_space(agent).sample()  # this is where you would insert your policy
    print(action)
    print(type(action))
    env.step(aa)
    # time.sleep(0.005)
    count = count + 1
    if count == 5:
        break

env.render()
env.close()

[0.71558774 0.8832722  0.9900449  0.5602077  0.03099385]
<class 'numpy.ndarray'>
[WARNING]: Received an action [0.0548357  0.         0.         0.02204804 0.        ] that was outside action space Box(0.0, 1.0, (5,), float32). Environment is clipping to space
[0.6107287  0.9918348  0.98018605 0.620316   0.6496268 ]
<class 'numpy.ndarray'>
[WARNING]: Received an action [0.0548357  0.         0.         0.02204804 0.        ] that was outside action space Box(0.0, 1.0, (5,), float32). Environment is clipping to space
[0.79844123 0.9156946  0.8545123  0.46651003 0.06465398]
<class 'numpy.ndarray'>
[WARNING]: Received an action [0.0548357  0.         0.         0.02204804 0.        ] that was outside action space Box(0.0, 1.0, (5,), float32). Environment is clipping to space
[0.04877817 0.6622239  0.8755051  0.17754623 0.46862632]
<class 'numpy.ndarray'>
[WARNING]: Received an action [0.0548357  0.         0.         0.02204804 0.        ] that was outside action space Box(0.0, 1.0, (5,),

Problems to solve: 
1. save videos [reference](https://github.com/fireofearth/cpsc533v_project/blob/c897af30921e13ac81ce01cc2a8066e1d46ecc31/colin/evaluate_tag_single_adversary.py)
3. try DQN
4. how to implement multiple network and train on that.

4. does the agent move fixed steps by each iteration in discrete mode
5. How to fix the landmark in fixed position, or is it just the rendering make it seem not staying where it is 


## Action, observation and State

In [5]:
s = env.reset()

# action space with four directions and stay

i = 0
# sample for different agents
for agent in env.agent_iter():
    a = env.action_space(agent).sample()
    print(agent, ':')
    # [no_action, move_left, move_right, move_down, move_up]
    print(env.action_space(agent))
    print(agent == 'adversary_0')
    env.step(a)
    print('sample action:', a)
    # print(env.observation_spaces)
    
    i = i + 1
    if i == 4:
        break

env.close()

adversary_0 :
Box(0.0, 1.0, (5,), float32)
True
sample action: [0.92901367 0.37396044 0.6046699  0.68962854 0.8919782 ]
adversary_1 :
Box(0.0, 1.0, (5,), float32)
False
sample action: [0.09669605 0.5639015  0.89365935 0.8282331  0.08617229]
adversary_2 :
Box(0.0, 1.0, (5,), float32)
False
sample action: [0.13027631 0.01165134 0.27997    0.39355087 0.16513759]
agent_0 :
Box(0.0, 1.0, (5,), float32)
False
sample action: [5.1456806e-04 9.9431151e-01 3.1835628e-01 4.3276712e-01 5.6209779e-01]


In [18]:
# state, should be 62?
env.state()

array([ 0.15303998,  0.03050993, -0.97915745, -0.28953764,  1.5197377 ,
        1.0614314 ,  1.2278101 ,  0.28194538,  0.6069736 ,  0.8174495 ,
        0.44835332,  0.46482474,  0.5754395 ,  1.1692449 ,  0.01615815,
       -0.00480299, -0.09565483,  0.11386324, -0.3721839 ,  0.5279119 ,
        0.9127642 ,  0.24398187,  0.6208366 , -0.53550416, -0.6069736 ,
       -0.8174495 , -0.15862025, -0.3526248 , -0.03153404,  0.35179535,
        0.01615815, -0.00480299, -0.14904232, -0.03848771, -0.53080416,
        0.17528708,  1.0713844 ,  0.5966067 ,  0.77945685, -0.18287934,
       -0.44835332, -0.46482474,  0.15862025,  0.3526248 ,  0.1270862 ,
        0.70442015,  0.01615815, -0.00480299,  0.01615815, -0.00480299,
       -0.40371794,  0.8797072 ,  0.94429827, -0.10781348,  0.65237063,
       -0.8872995 , -0.5754395 , -1.1692449 ,  0.03153404, -0.35179535,
       -0.1270862 , -0.70442015], dtype=float32)

In [29]:
env = simple_tag_v2.env(num_good=1, 
                        num_adversaries=3, 
                        num_obstacles=2, 
                        max_cycles=50, 
                        continuous_actions=True, 
                        render_mode="human"
)

In [6]:
# env.reset()
# obj = []
# i = 0
# for agent in env.agent_iter():
#
#     obj.append(agent)
#     env.step([1,1,1,1,1])
#     i = i + 1
#     if i == 4:
#         break

env.reset()
i = 0
for agent in env.agent_iter():

    print(agent, ':')
    env.step(env.action_space(agent).sample())
    # observation space: shape(14),(16)
    # Agent and adversary observations: [self_vel, self_pos, landmark_rel_positions, other_agent_rel_positions, other_agent_velocities]
    # observation function in the simple_tag.py: other_agent_rel_positions contains all agents except oneself, the order is adversary to agent, 
    # other_agent_velocities only for not adversary
    print(env.last())
    
    i = i + 1
    if i == 4:
        break

env.close()

adversary_0 :
[ 0.          0.         -0.05791276  0.3346408  -0.8086802   0.06578394
  0.7563633  -0.31174925 -0.6584351  -1.1056974   0.22030357 -1.2653029
  0.9858129  -0.24132617  0.          0.        ]
adversary_1 :
[ 0.          0.         -0.7163479  -0.77105653 -0.15024512  1.1714813
  1.4147984   0.79394805  0.6584351   1.1056974   0.87873864 -0.15960555
  1.644248    0.8643712   0.          0.        ]
adversary_2 :
[ 0.          0.          0.1623908  -0.9306621  -1.0289837   1.3310869
  0.53605974  0.9535536  -0.22030357  1.2653029  -0.87873864  0.15960555
  0.7655093   1.0239767   0.          0.        ]
agent_0 :
[ 0.16266285 -0.12010477  0.9441664   0.08130416 -1.8107594   0.3191206
 -0.24571589 -0.05841262 -1.0147394   0.24549443 -1.6538827  -0.8703886
 -0.7812546  -1.0105222 ]


## Policy network